export const YOLLAR = {
  anaSayfa: '/',
  tanitim: '/tanitim',
  giris: '/giris',
  sertifikaDogrula: '/sertifikalar/dogrula',
  epostaDogrula: '/eposta-dogrula',
  sifreDegistir: '/sifre-degistir',
  profil: '/profil',
  ayarlar: '/ayarlar',
  kulupler: '/kulupler',
  kulupDetay: (kulupId: string) => `/kulupler/${kulupId}`,
  bildirimler: '/bildirimler',
  mesajlar: '/mesajlar',
  kulupYonetimi: '/kulup-yonetimi',
  kulupEtkinlikYonetimi: (etkinlikId: string) => `/kulup-yonetimi/etkinlikler/${etkinlikId}`,
  tesisYonetimi: '/tesis-yonetimi',
  tesisRezervasyon: '/tesis-rezervasyon',
  rezervasyonlarim: '/rezervasyonlarim',
  yonetim: '/yonetim',
  duyuru: '/duyuru',
  yemek: '/yemek',
  yemekSiparislerim: '/yemek/siparislerim',
  isletmePaneli: '/isletme',
  campusRide: '/campusride',
  rideYonetimi: '/ride-yonetimi',
} as const;
